# Generated by Django 3.0.5 on 2020-04-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MachineId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('2', 'ACKNOWLEDGED'), ('3', 'RESOLVED')], default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.IncidentId')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.MachineId')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.Status')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.IncidentSummary')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.IncidentTitle')),
            ],
        ),
    ]
