# Generated by Django 3.0.5 on 2020-04-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20200406_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdetail',
            name='incident_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentdetail',
            name='machine_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentdetail',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Acknowledged', 'ACKNOWLEDGED'), ('Resolved', 'RESOLVED')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentdetail',
            name='summary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentdetail',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='IncidentId',
        ),
        migrations.DeleteModel(
            name='IncidentSummary',
        ),
        migrations.DeleteModel(
            name='IncidentTitle',
        ),
        migrations.DeleteModel(
            name='MachineId',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
