# Generated by Django 3.0.5 on 2020-04-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20200407_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdetail',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Very High', 'Very High')], default='Normal', max_length=100),
        ),
    ]
