# Generated by Django 3.0.5 on 2020-04-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_incidentdetail_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdetail',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Acknowledged', max_length=100),
        ),
    ]
