# Generated by Django 3.0.5 on 2020-04-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_auto_20200409_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdetail',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Active', max_length=100),
        ),
    ]
