# Generated by Django 3.0.5 on 2020-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_auto_20200409_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=100)),
                ('machine_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('Deployment_id', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Very High', 'Very High')], default='Normal', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Active', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='IncidentDetail',
        ),
    ]
