# Generated by Django 3.0.5 on 2020-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_auto_20200413_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidents',
            old_name='Deployment_id',
            new_name='deployment_id',
        ),
        migrations.AddField(
            model_name='incidents',
            name='category',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Very High', 'Very High')], default='Normal', max_length=100),
        ),
        migrations.AddField(
            model_name='incidents',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Low', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=100),
        ),
    ]
