# Generated by Django 3.0.5 on 2020-04-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_auto_20200413_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='incident_detail',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
