# Generated by Django 3.0.5 on 2020-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0009_incidents_incident_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='category',
            field=models.CharField(choices=[], default='Snapback', max_length=100),
        ),
    ]
