# Generated by Django 3.0.5 on 2020-04-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_auto_20200413_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='incident_id',
        ),
    ]
