# Generated by Django 3.0.5 on 2020-04-13 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_remove_incidents_incident_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='id',
        ),
        migrations.AddField(
            model_name='incidents',
            name='incident_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
