# Generated by Django 3.0.5 on 2020-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_auto_20200413_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
