# Generated by Django 3.0.5 on 2020-04-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0016_auto_20200413_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
