# Generated by Django 3.0.5 on 2020-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0017_auto_20200413_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='module',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='package',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
