# Generated by Django 2.2 on 2020-04-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0018_auto_20200414_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidents',
            options={'verbose_name': 'incident', 'verbose_name_plural': 'incidents'},
        ),
    ]
